### ISSUE TITLE
hi ,ImportError: No module named security

### ISSUE THREAD

**Issue by vTNT** [AnsiblePower/AnsiblePower#1]
Django version 1.7.10, using settings 'ansiblePower.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 64, in **call**
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 168, in **call**
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named security

my django version:17.10   how to solve it ?

**Comment by dborysenko** [comment]
Hello lin yd.
This project is currently in development stage. I dont recomend to use it
yet.
Now about your error:
I am developing on django 1.8.4 and dont try to support any other versions.
You can checkout my Vagrantfile and try to bring up things on it (that
vagrant file provision all dependencies).
9 окт. 2015 г. 11:38 пользователь "lin yd" notifications@github.com
написал:

**Comment by vTNT** [comment]
ok thanks 
if my django version is 1.8.x, i install  AnsiblePower, it will appear these warnings：
(1_8.W001) The standalone TEMPLATE_\* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DIRS, TEMPLATE_DEBUG.
so  i change the django version to 1.7.10

**Comment by dborysenko** [comment]
That warning is ok. In future i'll get rid of it.

2015-10-12 4:54 GMT+03:00 lin yd notifications@github.com:

**Comment by vTNT** [comment]
thanks
